repository_type: pipeline

nf_core_version: 3.5.1

lint:
  files_unchanged:
    - CODE_OF_CONDUCT.md
    - assets/nf-core-luscombeu_rrnascan_logo_light.png
    - docs/images/nf-core-luscombeu_rrnascan_logo_light.png
    - docs/images/nf-core-luscombeu_rrnascan_logo_dark.png
    - .github/ISSUE_TEMPLATE/bug_report.yml
    - .github/CONTRIBUTING.md
    - .github/PULL_REQUEST_TEMPLATE.md
    - assets/email_template.txt
    - docs/README.md
  nextflow_config:
    - manifest.name
    - manifest.homePage
  multiqc_config:
    - report_comment
  files_exist:
    - CODE_OF_CONDUCT.md
    - assets/nf-core-luscombeu_rrnascan_logo_light.png
    - docs/images/nf-core-luscombeu_rrnascan_logo_light.png
    - docs/images/nf-core-luscombeu_rrnascan_logo_dark.png
    - .github/ISSUE_TEMPLATE/config.yml
    - .github/workflows/awstest.yml
    - .github/workflows/awsfulltest.yml

template:
  org: oist
  name: LuscombeU_rrnascan
  description: Pipeline to scan sequencing reads and extract rRNA sequences including
    18S, 5.8S, ITS, 28S
  author: Johannes Nicolaus Wibisana
  version: 1.0.0dev
  force: true
  outdir: .
  skip_features:
    - gpu
  is_nfcore: false
